version: '3.8'

services:
    symfony:
        container_name: symfony_wg_device_rest
        build:
            context: .
        ports:
            -   '8888:8888'
        volumes:
            -   .:/var/www/wg_device_rest
        environment:
            APP_ENV: prod